apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: mariadb-2clusters

# Build configuration - builds images once for both clusters
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 1
  artifacts:
  - image: federated-k8s-auth
    context: federated-k8s-auth
    docker:
      dockerfile: Dockerfile
  - image: mariadb-server
    docker:
      dockerfile: Dockerfile.mariadb
      buildArgs:
        BUILDKIT_INLINE_CACHE: "1"
        CMAKE_OPTS: "-DUSE_TOKEN_VALIDATOR_API=ON"
  - image: test-client
    docker:
      dockerfile: Dockerfile.client
      buildArgs:
        BUILDKIT_INLINE_CACHE: "1"

# Deploy configuration - deploys to cluster-a only
deploy:
  kubeContext: kind-cluster-a
  kubectl: {}

manifests:
  rawYaml:
  # Cluster-A: MariaDB + Federated K8s Auth (multi-cluster mode)
  - k8s/cluster-a/namespace.yaml
  - k8s/cluster-a/rbac.yaml
  - k8s/cluster-a/mariadb-nodeport.yaml  # MariaDB deployment
  - k8s/cluster-a/test-clients.yaml      # Test clients for local testing
  - k8s/cluster-a/federated-k8s-auth-serviceaccount.yaml
  - k8s/cluster-a/federated-k8s-auth-configmap.yaml
  - k8s/cluster-a/federated-k8s-auth-deployment.yaml
  - k8s/cluster-a/federated-k8s-auth-service.yaml
  - k8s/cluster-a/federated-k8s-auth-networkpolicy.yaml

---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cluster-b-client

# Depend on main config for images
requires:
  - configs: ["mariadb-2clusters"]
    activeProfiles: []

# Deploy to cluster-b
deploy:
  kubeContext: kind-cluster-b
  kubectl: {}

manifests:
  rawYaml:
  - k8s/cluster-b/namespace.yaml
  - k8s/cluster-b/test-client-remote.yaml
