apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: mariadb-auth-k8s

# Build configuration
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 1
  artifacts:
  - image: mariadb-server
    docker:
      dockerfile: Dockerfile.mariadb
      buildArgs:
        BUILDKIT_INLINE_CACHE: "1"
  - image: test-client
    docker:
      dockerfile: Dockerfile.client
      buildArgs:
        BUILDKIT_INLINE_CACHE: "1"

# Deploy configuration
deploy:
  kubeContext: kind-cluster-a
  kubectl: {}

manifests:
  rawYaml:
  - k8s/cluster-a/namespace.yaml
  - k8s/cluster-a/rbac.yaml
  - k8s/cluster-a/mariadb-nodeport.yaml
  - k8s/cluster-a/test-clients.yaml
